# .github/workflows/terraform.yml

name: Terraform WordPress

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -var 'aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}' -var 'aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}' -var 'database_name=${{ secrets.DATABASE_NAME }}' -var 'database_password=${{ secrets.DATABASE_PASSWORD }}' -var 'database_user=${{ secrets.DATABASE_USER }}'
